### PR TITLE
Manifest File Creation Fix

### LINKED ISSUE #16: Manifest file creating wrong structure
Manifest file creation is returning
`{ "website.json": "hash",
...
}`

Instead it should return 
`{ "website.json":  {
hashType: 'sha512',
hashValue: 'hash'
},
...
}`

I created the fix but im not allowed to push to a branch and therefore cant create a pull request

### PR DESCRIPTION
**Pull request by raymondflores**
[new changes for manifest file](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW6)
fixes #16

### CODE REVIEW

**Comment by raymondflores** [comment]
@kobim I reverted the files the test worked on utils.test.js but was breaking for other reason i could not figure out

**Comment by raymondflores** [comment]
screen shot 2018-08-07 at 2 17 12 pm

I've tried npm install/npm rebuild

**Comment by kobim** [comment]
It's strange your nodejs is trying to run the global _jest_ rather then local. Maybe your NODE_ENV is set to production?
Try this in the project root (verify your npm version is 5 or above):
```sh
rm -rf node_modules/
NODE_ENV=development npm install
npm test
```
and let me know if you succeed.

**Comment by raymondflores** [comment]
screen shot 2018-08-08 at 11 09 17 am
Did not work @kobim

**Comment by raymondflores** [comment]
Can you checkout my fork and see if test run well on your side @kobim

**Comment by raymondflores** [comment]
without this fix this library does not even work

**Comment by kobim** [comment]
Merged & published to npm.
Thank you for your contribution!

**Pull request merged**
